param(
    [Parameter(Mandatory = $true)]
    [string]$ImagePath,
    [Parameter(Mandatory = $true)]
    [string]$OutPath
)

$ErrorActionPreference = "Stop"

# Must stay in sync with frontend/src/utils/supportQrSecure.js
$KeyMaterial = "FlowX-SupportQr-v1"

function Get-SupportQrKeyBytes {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        return $sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($KeyMaterial))
    } finally {
        $sha.Dispose()
    }
}

function Get-Sha256Hex {
    param([byte[]]$Bytes)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hash = $sha.ComputeHash($Bytes)
        return ([BitConverter]::ToString($hash)).Replace("-", "").ToLowerInvariant()
    } finally {
        $sha.Dispose()
    }
}

function Encrypt-Aes256Cbc {
    param([byte[]]$PlainBytes)
    $key = Get-SupportQrKeyBytes
    $aes = [System.Security.Cryptography.Aes]::Create()
    try {
        $aes.Mode = [System.Security.Cryptography.CipherMode]::CBC
        $aes.Padding = [System.Security.Cryptography.PaddingMode]::PKCS7
        $aes.KeySize = 256
        $aes.Key = $key
        $aes.GenerateIV()
        $encryptor = $aes.CreateEncryptor()
        try {
            $cipher = $encryptor.TransformFinalBlock($PlainBytes, 0, $PlainBytes.Length)
        } finally {
            $encryptor.Dispose()
        }
        return @{
            Iv = $aes.IV
            Ciphertext = $cipher
        }
    } finally {
        $aes.Dispose()
    }
}

if (-not (Test-Path -LiteralPath $ImagePath)) {
    throw "Support QR image not found: $ImagePath"
}

$plain = [System.IO.File]::ReadAllBytes($ImagePath)
if ($plain.Length -lt 8) {
    throw "Support QR image is too small or empty."
}

$magic = ($plain[0..3] | ForEach-Object { '{0:X2}' -f $_ }) -join ''
$mime = $null
if ($magic -eq "89504E47") {
    $mime = "image/png"
} elseif ($plain.Length -ge 3 -and $plain[0] -eq 0xFF -and $plain[1] -eq 0xD8 -and $plain[2] -eq 0xFF) {
    $mime = "image/jpeg"
} else {
    throw "Support QR source must be a PNG or JPEG image."
}

$enc = Encrypt-Aes256Cbc -PlainBytes $plain
$sha256 = Get-Sha256Hex -Bytes $plain
$ivB64 = [Convert]::ToBase64String($enc.Iv)
$cipherB64 = [Convert]::ToBase64String($enc.Ciphertext)

$outDir = Split-Path -Parent $OutPath
if ($outDir -and -not (Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$js = @"
/** @generated by scripts/Generate-SupportQrPayload.ps1 — do not edit by hand */
export const SUPPORT_QR_PAYLOAD = {
  v: 1,
  alg: 'aes-256-cbc',
  mime: '$mime',
  iv: '$ivB64',
  ciphertext: '$cipherB64',
  sha256: '$sha256',
};
"@

Set-Content -LiteralPath $OutPath -Value $js -Encoding UTF8 -NoNewline
Write-Host "Wrote encrypted support QR payload: $OutPath"
exit 0
