#Requires -Version 5.1
<#
.SYNOPSIS
  Finalize a plaintext distribution export: license embed, online-auth modules, marker file.

.DESCRIPTION
  Run after export_cim.ps1 (no -HardenAll) and before build_installer.ps1.
  Does NOT encrypt server or JS — files remain readable on the client install.
#>
[CmdletBinding()]
param(
    [string]$ExportRoot = "",
    [string]$RepoRoot = "",
    [string]$LicenseSecret = ""
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $ScriptDir "Get-CiMPaths.ps1")
if (-not $RepoRoot) { $RepoRoot = Split-Path -Parent $ScriptDir }
$pkg = Get-CiMPackagePaths -RepoRoot $RepoRoot
if (-not $ExportRoot) {
    $fx = Get-CiMPaths -RepoRoot $RepoRoot -DistributionKind Plaintext
    $ExportRoot = $fx.ExportRoot
} else {
    if (-not [System.IO.Path]::IsPathRooted($ExportRoot)) {
        $ExportRoot = Join-Path $RepoRoot $ExportRoot
    }
    $ExportRoot = [System.IO.Path]::GetFullPath($ExportRoot)
    $fx = Resolve-CiMPathsForExportRoot -ExportRoot $ExportRoot -RepoRoot $RepoRoot -DefaultKind Plaintext
}

$secret = Get-CiMVendorSecret -LicenseSecret $LicenseSecret -RepoRoot $RepoRoot
if (-not $secret) {
    throw @"
CIM_LICENSE_SECRET or config\.build_license_secret embeds distribution crypto on the build machine (clients use online sign-in).

Set: `$env:CIM_LICENSE_SECRET = 'your-secret'
Or save one line in config\.build_license_secret
"@
}
$env:CIM_LICENSE_SECRET = $secret

$baseRequired = @("start_cim.bat", "data\nse_data.db", "runtime\python\python.exe")
$baseMissing = @()
foreach ($rel in $baseRequired) {
    if (-not (Test-Path -LiteralPath (Join-Path $ExportRoot $rel))) { $baseMissing += $rel }
}
if ($baseMissing.Count -gt 0) {
    throw @"
Export tree is missing core files: $($baseMissing -join ', ')

Run a full plaintext build (do not use -SkipExport):
  .\Build-CiM-Plaintext.bat

Or export first:
  .\export_cim.ps1 -Mode distribution -PlaintextDistribution
"@
}

function Write-CiMEmbeddedDistSecret {
    param([string]$Root, [string]$Secret)
    $mask = [System.Text.Encoding]::UTF8.GetBytes("CiM-embed-v1!!")
    $secretBytes = [System.Text.Encoding]::UTF8.GetBytes($Secret)
    $obf = New-Object System.Collections.Generic.List[int]
    for ($i = 0; $i -lt $secretBytes.Length; $i++) {
        $obf.Add($secretBytes[$i] -bxor $mask[$i % $mask.Length])
    }
    $tuple = ($obf | ForEach-Object { "$_" }) -join ", "
    $utf8 = New-Object System.Text.UTF8Encoding $false
    $embeddedPath = Join-Path $Root "server\_cim_dist_embedded.py"
    $content = @"
# AUTO-GENERATED by Prepare-CiMPlaintextExport.ps1 — do not edit.
"""Build-time embedded distribution secret (plaintext distribution build)."""
from __future__ import annotations

_OBF = ($tuple)
_MASK = b"CiM-embed-v1!!"


def distribution_secret_bytes() -> bytes:
    return bytes(_OBF[i] ^ _MASK[i % len(_MASK)] for i in range(len(_OBF)))
"@
    [System.IO.File]::WriteAllText($embeddedPath, $content, $utf8)
    Write-Host "Wrote server\_cim_dist_embedded.py"
}

# Strip encrypted artifacts only under server/ and frontend JS (never scan whole export tree).
foreach ($rel in @("server", "frontend\build\static\js")) {
    $dir = Join-Path $ExportRoot $rel
    if (-not (Test-Path -LiteralPath $dir)) { continue }
    Get-ChildItem -Path $dir -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -match '\.(pyc|js)\.enc$' } |
        ForEach-Object {
            Remove-Item -LiteralPath $_.FullName -Force
            Write-Host "Removed encrypted artifact: $($_.FullName.Substring($ExportRoot.Length))"
        }
}

Write-CiMEmbeddedDistSecret -Root $ExportRoot -Secret $secret

# Readable server sources from repo (replaces encrypted .pyc.enc from prior builds).
$serverSrc = $pkg.ServerRoot
$serverDst = Join-Path $ExportRoot "server"
if (Test-Path -LiteralPath $serverSrc) {
    Get-ChildItem -LiteralPath $serverSrc -File -Filter "*.py" -ErrorAction SilentlyContinue |
        ForEach-Object {
            Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $serverDst $_.Name) -Force
        }
    Write-Host "Synced server\*.py from repo (readable plaintext)"
}

$plainSync = @(
    "config\product.json",
    "desktop\main.js",
    "desktop\preload.js"
)
foreach ($rel in $plainSync) {
    if ($rel -like "desktop\*") {
        $src = Join-Path $pkg.DesktopRoot ($rel -replace '^desktop\\', '')
    } else {
        $src = Join-Path $RepoRoot $rel
    }
    $dst = Join-Path $ExportRoot $rel
    if (-not (Test-Path -LiteralPath $src)) {
        Write-Warning "Skip missing repo file: $rel"
        continue
    }
    $parent = Split-Path -Parent $dst
    if ($parent -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    Copy-Item -LiteralPath $src -Destination $dst -Force
    Write-Host "Synced $rel"
}

# Plaintext export already built frontend with REACT_APP_EXPORT_MODE=distribution in export_cim.ps1.
# Only rebuild if the export bundle is missing (e.g. -SkipExport on a stale tree).
$frontendBuildDst = Join-Path $ExportRoot "frontend\build"
if (-not (Test-Path -LiteralPath (Join-Path $frontendBuildDst "index.html"))) {
    if (-not (Test-Path -LiteralPath (Join-Path $pkg.BrowserRoot "package.json"))) {
        throw "Missing frontend\build in export and no packages\browser\package.json in repo."
    }
    Write-Host "Building browser package (distribution profile, readable JS)..."
    Invoke-CiMBrowserProductionBuild -BrowserRoot $pkg.BrowserRoot -DistributionMode
    $frontendBuildSrc = $pkg.BrowserBuild
    if (-not (Test-Path -LiteralPath $frontendBuildDst)) {
        New-Item -ItemType Directory -Force -Path $frontendBuildDst | Out-Null
    }
    robocopy $frontendBuildSrc $frontendBuildDst /E /NFL /NDL /NJH /NJS /nc /ns /np | Out-Null
    Write-Host "Synced frontend\build from repo (readable JS bundle)"
}

$authSrc = $pkg.BrowserAuth
$authDst = Join-Path $ExportRoot "frontend\auth"
if (Test-Path -LiteralPath $authSrc) {
    if (Test-Path -LiteralPath $authDst) { Remove-Item -LiteralPath $authDst -Recurse -Force }
    Copy-Item -LiteralPath $authSrc -Destination $authDst -Recurse -Force
    Write-Host "Synced frontend\auth"
}

$configDir = Join-Path $ExportRoot "config"
if (-not (Test-Path -LiteralPath $configDir)) {
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
}
$markerPath = Join-Path $configDir ".cim-plaintext-dist"
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($markerPath, "plaintext distribution build`n", $utf8NoBom)
Write-Host "Wrote config\.cim-plaintext-dist"

& (Join-Path $ScriptDir "Prepare-CiMOnlineDistribution.ps1") -ExportRoot $ExportRoot -RepoRoot $RepoRoot
if ($LASTEXITCODE -ne 0) { throw "Prepare-CiMOnlineDistribution failed" }

# Never ship build-time vendor profile on client installs.
foreach ($name in @(".fx-dist.cfg", ".flowx_vendor_secret")) {
    $p = Join-Path $configDir $name
    if (Test-Path -LiteralPath $p) { Remove-Item -LiteralPath $p -Force }
}

$required = @(
    "start_cim.bat",
    "data\nse_data.db",
    "frontend\build\index.html",
    "frontend\auth\index.html",
    "runtime\python\python.exe",
    "server\cim_bootstrap.py",
    "server\app_code_crypto.py",
    "server\server.py",
    "server\license_client.py",
    "server\license_routes.py",
    "config\product.json",
    "config\.cim-plaintext-dist",
    "config\.cim-online-only"
)
$missing = @()
foreach ($rel in $required) {
    if (-not (Test-Path -LiteralPath (Join-Path $ExportRoot $rel))) { $missing += $rel }
}
if ($missing.Count -gt 0) {
    throw "Plaintext export incomplete. Missing: $($missing -join ', ')"
}

$verify = Join-Path $ScriptDir "Verify-CiMLicenseChain.ps1"
if (Test-Path -LiteralPath $verify) {
    & powershell -NoProfile -ExecutionPolicy Bypass -File $verify `
        -ExportRoot $ExportRoot -RepoRoot $RepoRoot -InstallerOutputDir $fx.InstallerOutputDir
    if ($LASTEXITCODE -ne 0) { throw "Verify-CiMLicenseChain failed" }
}

Write-Host "Plaintext export prepared: $ExportRoot"
